apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-config
  namespace: {{ .Values.webapp.namespace }}
data:
  WEBAPP_DB_URL: {{ .Values.db.DATABASE_URL }}
  FLYWAY_URL: {{ .Values.db.DB_URL }}
  FLYWAY_USER: {{ .Values.db.username }}
  FLYWAY_PASSWORD: {{ .Values.db.password }}
  FLYWAY_SCHEMAS: {{ .Values.db.schema }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kafka-config
  namespace: {{ .Values.webapp.namespace }}
data:
  KAFKA_BROKER_ADDRESSES: {{ include "KAFKA_BROKER_ADDRESS" .}}
  KAFKA_TOPIC: {{ .Values.kafka.topic }}