apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }} 
  encrypted: {{ .Values.storageClass.parameters }}  
  kmsKeyId: {{ .Values.storageClass.kms_id }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
